[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-gatsby"
  pinned_version = "4.40.2"

[context.production.environment]
  # Use Netlify’s preinstalled Sharp binary
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"