[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-gatsby"
  version = "4.40.2"