backend:
  name: git-gateway
  branch: cms
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "members"
    label: "Members"
    folder: "src/pages/members"
    description: "These are the members currently in CMUBTG."
    slug: "{{andrewID}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "member",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "AndrewID", name: "andrewID", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Photo", name: "photo", widget: image }
      - { label: "Portfolio", name: "portfolio", widget: "markdown" }
      - { label: "Resume", name: "resume", widget: "file" }
      - { label: "Year", name: "year", widget: "number", value_type: "int" }
      - { label: "Degree", name: "degree", widget: "select", options: ["BS", "MS"] }
      - { label: "Major", name: "major", widget: "string" }
      - { label: "LinkedIn", name: "linkedIn", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    description: "These are the current projects for CMUBTG."
    slug: "{{title}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Photo", name: "photo", widget: image }
      - { label: "DescriptionPhoto", name: "descriptionPhoto", widget: image }
      - { 
          label: "Members", 
          name: "members", 
          widget: "relation",
          collection: "members",
          value_field: "({{fields.title}}, {{fields.andrewID}}, {{fields.photo}}, {{fields.role}})",
          search_fields: ["title", "andrewID"],
          display_fields: ["title","role"],
          multiple: true
        }
                     
  - name: "alumni"
    label: "Alumni"
    folder: "src/pages/alumni"
    description: "There are the CMUBTG alumni."
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "alumni",
        }
      - { label: "Title", name: "title", widget: "string"}
      - { label: "LinkedIn", name: "linkedIn", widget: "string" }
      - { label: "Year", name: "year", widget: "number", value_type: "int" }
      - { label: "Degree", name: "degree", widget: "select", options: ["BS", "MS"] }
      - { label: "Major", name: "major", widget: "string" }
      - { label: "Role", name: "role", widget: "string"}
      - { label: "Photo", name: "photo", widget: image }
